### ISSUE TITLE
Milestone 8: Architecture

### ISSUE THREAD

**Issue by austinjfreed** [SCCapstone/Code-Commandos#24]
Deliverables
- [x] The Models for your app. These could be UML class diagrams, or just models with attributes (with type) and descriptions (in English).
- [x] How will your app maintain state? in memory? or database? or both? Note this in your Model Classes.
- [x] If you are using a db-backend (say firebase) then include the Database schema: set of tables/documents with list of attributes and their types
List of common queries you expect will be needed. Do any of then need to join tables?
- [x] The Views of your app: name, describe, link each (actual hyperlink) to its image in your Detailed Design milestone if application. Typically, one page in the app is composed of multiple View elements.
- [x] The Database schema: set of tables/documents with list of attributes and their types. Describe each table and attribute in English.
- [x] List of common queries you expect will be needed. Do any of then need to join tables?
- [x] Are all the images (if any) embedded in the wiki page? and hosted at github?
- [x] Is the wiki page easy to read?
